version: '3.0'
services:
  spa-service:
    image: bstraehle/spa
    ports:
      - 8080:80
    depends_on:
      - restapi-service
    networks:
      - front-end
      - back-end
    deploy:
      replicas: 1
  restapi-service:
    image: bstraehle/rest-api
    ports:
      - 8001:80
    networks:
      - back-end
    deploy:
      replicas: 1
networks:
  front-end:
  back-end:
